server:
  port: 8084

logging:
  level:
    org:
      apache:
        kafka: OFF

spring:
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      orchestrator: orchestrator
      inventory-success: inventory-success
      inventory-failure: inventory-failure
    consumer:
      group-id: inventory-group
      auto-offset-reset: latest

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/inventory-db
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: create-drop

  banner:
    location: banner.txt