server:
  port: 8082

logging:
  level:
    org:
      apache:
        kafka: OFF

spring:
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      orchestrator: orchestrator
      product-success: product-success
      product-failure: product-failure
    consumer:
      group-id: product-group
      auto-offset-reset: latest

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/product-db
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: create-drop

  banner:
    location: banner.txt