server:
  port: 8083

logging:
  level:
    org:
      apache:
        kafka: OFF

spring:
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      orchestrator: orchestrator
      payment-success: payment-success
      payment-failure: payment-failure
    consumer:
      group-id: payment-group
      auto-offset-reset: latest

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/payment-db
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: create-drop

  banner:
    location: banner.txt